# Generated by Django 4.2.16 on 2025-09-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_archivo_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='storage/propiedades/')),
                ('precio', models.PositiveIntegerField()),
                ('comuna', models.CharField(choices=[('Santiago', 'Santiago'), ('Providencia', 'Providencia'), ('Las Condes', 'Las Condes'), ('Ñuñoa', 'Ñuñoa'), ('Vitacura', 'Vitacura'), ('Lo Barnechea', 'Lo Barnechea'), ('La Florida', 'La Florida'), ('Puente Alto', 'Puente Alto'), ('Maipú', 'Maipú'), ('San Miguel', 'San Miguel'), ('Recoleta', 'Recoleta'), ('Independencia', 'Independencia')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
