# Generated by Django 4.2.16 on 2025-09-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='vistas',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
